image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank-build-for-testers.jar -port=7777 -P:profile=test &



build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true
